- name: Create HDFS directory for vagrant
  shell: source /etc/profile && hdfs dfs -mkdir -p /user/vagrant
  args:
    executable: /bin/bash
  tags:
    - hdfs_config

- name: chown /user/vagrant
  shell: source /etc/profile && hdfs dfs -chown vagrant /user/vagrant
  args:
    executable: /bin/bash
  tags:
    - hdfs_config