#
# GUI Playbook
#

- name: Configure Ambari Agent
  lineinfile: dest=/etc/X11/Xwrapper.config regexp='^allowed_users=' line='allowed_users=anybody'
  sudo: yes
  tags:
    - gui_xfce

- name: Install xcfe and VirtualBox guest additions
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - xfce4
    - virtualbox-guest-dkms 
    - virtualbox-guest-utils 
    - virtualbox-guest-x11
    - gnome-icon-theme-full 
    - tango-icon-theme
  tags:
    - gui_xfce

# - name: Confiure gdm
#   shell: dpkg-reconfigure gdm
#   sudo: yes
#   tags:
#     - gui_xfce

# - name: Check to see if the guest additions has already been downloaded
#   stat: path=/root/VBoxGuestAdditions_{{ virtualbox_version }}.iso
#   sudo: yes
#   register: guest_additions_downloaded
#   tags:
#     - gui_xfce

# - name: Download guest additions {{ guest_additions }}
#   get_url: url={{ guest_additions }} dest=/root/VBoxGuestAdditions_{{ virtualbox_version }}.iso
#   sudo: yes
#   when: guest_additions_downloaded.stat.exists == False
#   tags:
#     - gui_xfce

# - name: Mount and install the guest additions
#   shell: mount -o loop /root/VBoxGuestAdditions_{{ virtualbox_version }}.iso /mnt/; /mnt/VBoxLinuxAdditions.run; umount /mnt
#   sudo: yes
#   tags:
#     - gui_xfce

# - name: Confiure VirtualBox guest additions
#   shell: sudo VBoxClient --clipboard --draganddrop --display --checkhostversion --seamless -d
#   sudo: yes
#   tags:
#     - gui_xfce

# - name: Start xfce
#   shell: nohup startxfce4 &
#   tags:
#     - gui_xfce
