#
# Install the Ambari server
#

- block:
  - name: Create Ambari Repo {{ ambari_repo }}
    get_url: url={{ ambari_repo }} dest=/etc/apt/sources.list.d/ambari.list

  - name: Update the key server
    apt_key: keyserver=keyserver.ubuntu.com id=B9733A7A07513CAD

  - name: Install Ambari Server
    apt: name=ambari-server update_cache=yes

  - name: Get Ambari's status
    command: ambari-server status
    register: ambari_status
    ignore_errors: yes

  - name: Configure Ambari Server
    command: ambari-server setup -s
    when: ambari_status.stdout | search('.*Ambari Server not running.*')

  - name: Start Ambari Server
    service: name=ambari-server state=restarted
    when: ambari_status.stdout | search('.*Ambari Server not running.*')

  - name: Wait for Ambari Server to start
    wait_for: port={{ ambari_server_port }} delay=10 timeout=60
    when: ambari_status.stdout | search('.*Ambari Server not running.*')

  become: true
  become_method: sudo
  tags:
    - ambari_server_install