---
- hosts: all
  max_fail_percentage: 0
  roles:
    - common
    - ssh_no_password
    - ambari_server
    - ambari_agent
    - hdp_single_node
    - configure_hdfs
    - gui
    - dev_tools
    - eclipse_scala_ide