---
#
# Enable passwordless ssh between machines
#

- name: Check to see if SSH keys have already been generated
  stat: 
    path: "{{ansible_env.HOME }}/.ssh/id_rsa"
  register: ssh_key
  tags:
    - ssh_no_password

- name: Generate SSH keys for passwordless SSH
  shell: "ssh-keygen -N '' -f {{ansible_env.HOME }}/.ssh/id_rsa"
  when: ssh_key.stat.exists == False
  tags:
    - ssh_no_password

- name: Add SSH Public Key to the authorized_keys file
  shell: cat {{ansible_env.HOME }}/.ssh/id_rsa.pub >> {{ansible_env.HOME }}/.ssh/authorized_keys
  when: ssh_key.stat.exists == False
  tags:
    - ssh_no_password

- name: Add fingerprint to known_hosts
  shell: ssh-keyscan -H localhost >> {{ansible_env.HOME }}/.ssh/known_hosts
  when: ssh_key.stat.exists == False
  tags:
    - ssh_no_password

- name: Add fingerprint to known_hosts
  shell: ssh-keyscan -H 0.0.0.0 >> {{ansible_env.HOME }}/.ssh/known_hosts
  when: ssh_key.stat.exists == False
  tags:
    - ssh_no_password