#
# Enable passwordless ssh between machines
#

- name: Check to see if SSH keys have already been generated
  stat: path=/root/.ssh/id_rsa
  become: yes
  register: ssh_key
  tags:
    - ssh_no_password

- name: Generate SSH keys for passwordless SSH
  shell: ssh-keygen -N '' -f /root/.ssh/id_rsa
  become: yes
  when: ssh_key.stat.exists == False
  tags:
    - ssh_no_password

- name: Add SSH Public Key to the authorized_keys file
  shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
  become: yes
  when: ssh_key.stat.exists == False
  tags:
    - ssh_no_password
